#!/bin/bash

_demo_all()
{
  local available="install setup login project load get delete ephemeral hostpath volatile resilient distributed usage"
  local available2=" "
  local availableSetup="cluster project"
  local availableDemoMode="start watch ps ls delete"
  local availableDelete="all"
    if [ "${COMP_WORDS[1]}" == "setup" ]; then
      available2=$availableSetup
    elif [ "${COMP_WORDS[1]}" == "delete" ]; then
      available2=$availableDelete
    elif [[ "${COMP_WORDS[1]}" == "ephemeral" || 
           "${COMP_WORDS[1]}" == "hostpath" ||
           "${COMP_WORDS[1]}" == "volatile" || 
           "${COMP_WORDS[1]}" == "resilient" || 
           "${COMP_WORDS[1]}" == "distributed" ]]; then
      available2=$availableDemoMode
    fi
  local suggestions=($(compgen -W "$available" "${COMP_WORDS[1]}"))
  local suggestions2=($(compgen -W "$available2" "${COMP_WORDS[2]}"))
  if [ "${COMP_CWORD}" == "0" ]; then
      COMPREPLY=("${suggestions[@]}")
  elif [ "${COMP_CWORD}" == "1" ]; then
    if [ "${#suggestions[@]}" == "1" ]; then
      local number=$(echo ${suggestions[0]/%\ */})
      COMPREPLY=("$number")
    else
      COMPREPLY=("${suggestions[@]}")
    fi
  elif [ "${COMP_CWORD}" == "2" ]; then
    if [ "${#suggestions2[@]}" == "1" ]; then
      local number=$(echo ${suggestions2[0]/%\ */})
      COMPREPLY=("$number")
    else
      COMPREPLY=("${suggestions2[@]}")
    fi
  else
    return 0;
  fi
  return 0;
}

complete -F _demo_all startx-demo
